version: '3'

services:
  glauth:
    image: glauth/glauth
    volumes:
      - ./glauth.conf:/app/config/config.cfg
  ejabberd:
    image: ejabberd/ecs:20.12
    volumes:
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml
    ports:
      - 5222:5222
